# Образ с Docker Hub: https://hub.docker.com/r/pboldev/tg-ws-proxy

# TG_WS_TIMEOUT — таймаут TCP+TLS+WS; при проблемах только в Docker см. README и оверлеи:
#   docker-compose.mtu.yml | docker-compose.dns.yml | docker-compose.host.yml (Linux)

services:
  tg-ws-proxy:
    container_name: tg-ws-proxy
    image: pboldev/tg-ws-proxy:2.2
    restart: unless-stopped
    ports:
      - "${TG_PORT:-1080}:${TG_PORT:-1080}"
    command:
      - "--host"
      - "${TG_HOST:-0.0.0.0}"
      - "--port"
      - "${TG_PORT:-1080}"
      - "--ws-timeout"
      - "${TG_WS_TIMEOUT:-10}"
      - "--dc-ip"
      - "${TG_DC_IP_1:-2:149.154.167.220}"
      - "--dc-ip"
      - "${TG_DC_IP_2:-4:149.154.167.220}"
      # Чтобы включить логирование:
      # - "--verbose"
      #
      # Чтобы добавить secret (можно несколько):
      # - "--secret"
      # - "f43b08aef31a50b7b92c17f07bb66b11"
